/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package autoresponder;

import static spark.Spark.*;

import com.twilio.twiml.messaging.Message;
import com.twilio.twiml.MessagingResponse;

public class App {

    public static void main(String[] args) {
        post("/auto-responder", (req, res) -> {
            final String body = req.queryParams("Body");
            System.out.println("Body is:" + body);
            res.type("application/xml");
            Message message;
            if (body.toUpperCase().equals("QUEST")) {
                message = new Message.Builder(
                        "Discover your power to change the world with code! https://twilio.com/quest").build();
            } else {
                message = new Message.Builder("I don't know what you mean by " + body + ". Did you mean QUEST?")
                        .build();
            }
            MessagingResponse twiml = new MessagingResponse.Builder().message(message).build();
            return twiml.toXml();

        });
    }
}
